var OverlayShader = [
    "varying vec2 textureCoordinate;",
    "",
    "uniform sampler2D inputImageTexture;",
    "uniform sampler2D overlayTexture;",
    "uniform bool flipX;",
    "",
    "void main() {",
    "    vec2 xy = textureCoordinate.xy;",
    "",
    "    if (flipX) {",
    "        xy.x = 1.0 - xy.x;",
    "    }",
    "",
    "    vec4 color = texture2D(inputImageTexture, xy);",
    "",
    "    vec4 colorO = texture2D(overlayTexture, xy);",
    "",
    "    color.rgb = mix(color.rgb, colorO.rgb, colorO.a);",
    "",
    "    if (colorO.a > color.a) {",
    "        color.a = colorO.a;",
    "    }",
    "",
    "    gl_FragColor = color;",
    "}",
    ""
].join('\n');